### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ghost** [vhanla/vscode-borderless#1]
?

**Comment by vhanla** [comment]
Maybe restoring and maximizing again would adjust it according to the new borderless new size.
Using hotkeys Win+DownArrow and Win+UpArrow  will still work.

**Comment by qawsqs** [comment]
That works, but it's a bit annoying to do every time. Also, is there an option to always start vs code borderless by default?

**Comment by vhanla** [comment]
Thanks for your feedback, I updated the extension and now it includes options to autoenable it on Code's startup as well it fixes this issue on maximized window size.

There is another option to select border mode. It also excluded Developer Tools window (if is detached). 

Please read the [readme file](../blob/master/README.md)
