### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by JamesDAdams** [vhanla/vscode-borderless#3]
This extension doesn't work anymore with the last version of vscode :/

**Comment by vhanla** [comment]
I can't reproduce it, it might be something on your installation or operating system, this only works on Windows. Currently working fine on Windows 10/11, as of current latest VSCode version.

**Comment by JamesDAdams** [comment]
Vscode : 1.75.1
Windows 10 : 19045.2604

Doesn't work
